name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET environment for .NET 9
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Ensure .NET 9 is used

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build and publish the project to a single executable
    - name: Build and publish
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true

    # Archive the built executable
    - name: Archive the executable
      run: |
        mkdir -p artifacts
        cp ./[ProjectFolderName]/bin/Release/net9.0-windows/win-x64/publish/*.exe artifacts/

    # Upload the artifact to the GitHub Release
    - name: Create Release and Upload Artifact
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
